build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:14.0.2"
  amd64: "ghcr.io/hassio-addons/base/amd64:14.0.2"
  armhf: "ghcr.io/hassio-addons/base/armhf:14.0.2"
  armv7: "ghcr.io/hassio-addons/base/armv7:14.0.2"
  i386: "ghcr.io/hassio-addons/base/i386:14.0.2"
labels:
  org.opencontainers.image.title: "Supervisor API Proxy"
  org.opencontainers.image.description: "RESTful API proxy for Home Assistant Supervisor"
  org.opencontainers.image.source: "https://github.com/your-username/supervisor-api-proxy"
  org.opencontainers.image.authors: "Your Name <your.email@example.com>"
  org.opencontainers.image.licenses: "MIT"