name: "Supervisor API Proxy"
description: "A REST API proxy for Home Assistant Supervisor to enable external access from Android apps and other clients"
version: "1.0.0"
slug: "supervisor_api_proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
boot: manual
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "API proxy web server"

options:
  log_level: info
  cors_origins:
    - "*"
  port: 8099
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem

schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  cors_origins:
    - str
  port: int(1024,65535)
  ssl: bool
  certfile: str?
  keyfile: str?

panel_icon: mdi:api
panel_title: "Supervisor API Proxy"
panel_admin: true

host_network: true
homeassistant_api: true
hassio_api: true
supervisor: true

environment:
  LOG_LEVEL: info

image: "ghcr.io/homeassistant/{arch}-addon-supervisor-proxy"