name: "Supervisor API Proxy"
version: "1.2.0"
slug: "supervisor_api_proxy"
description: "RESTful API proxy for Home Assistant Supervisor functions"
url: "https://github.com/your-username/supervisor-api-proxy"
startup: application
boot: manual
init: false
map:
  - config:rw
ports:
  "8080/tcp": 8080
ports_description:
  "8080/tcp": "API Proxy Port"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
hassio_role: admin
options:
  log_level: "info"
  cors_origins: []
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  cors_origins: "[str]?"
image: "supervisor-api-proxy/{arch}"