name: "Supervisor API Proxy"
description: "A REST API proxy for Home Assistant Supervisor to enable external access from Android apps and other clients"
version: "1.0.0"
slug: "supervisor_api_proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
boot: manual
ingress: true
ingress_port: 8099
ingress_entry: "/api/v1"

options:
  log_level: info
  cors_origins:
    - "*"
  port: 8099
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem

schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  cors_origins:
    - str
  port: int(1024,65535)
  ssl: bool
  certfile: str?
  keyfile: str?

panel_icon: mdi:api
panel_title: "Supervisor API Proxy"
panel_admin: true

homeassistant_api: true
hassio_api: true
hassio_role: admin
supervisor: true
docker_api: true
privileged: 
  - SYS_ADMIN
auth_api: true
full_access: true
all_addon_configs: true

environment:
  LOG_LEVEL: info